version: "3.8"

services:
    start-page:
        container_name: excalith-start-page
        image: excalith/start-page
        restart: unless-stopped
        networks:
            - proxy
        volumes:
            - data:/app/data

networks:
    proxy:
        external: true

volumes:
    data:
        name: excalith-start-page
